language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.10.x
  - go: 1.11.x
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
install:
- 
script:
- go get -t -v ./...
- go test -v -race -covermode=count -coverprofile=coverage.out ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="builds/{{.Dir}}_{{.OS}}_{{.Arch}}"
  -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
- if [ "${LATEST}" = "true" ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN ; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Fq2aMxZorqyT3omuUucBx0Je5LXJ70xEzEuLmZL4jVK4nRoGVLoZH/v6RaqSmeD3J1kD4Um/w8jweqcRbCc/zw5uMFB+3IGLZPK/F9NtTeMMoTAkDL8zBECHIdMCFvmAtQoLrBFvl8M9toUnQsm+/3mmtLWrRdFn6u0HrTTXf9jM3C/QG+nDSG5g/KBHZATHC7KWRcP1n9UG+UILCJCB1dMmRWmaN0qvQdFDpXermQ4gveDFaIuwNXoi4kz1Oza60c9ODupCejoiQelDIcUqFrSDhVgw6IAH3zhzfri4dN0835euwFwuS2dpqzzT8KGrM0VTEIcgYTwktnCru4WSSacdu1COsLahK+FN1fKk8+vzFvQ0pSoSor9/mFsr6R3PXXf1k7X/kC10SBV41oQTVsLDBR9S6rebyglWZVfw9snY89/sZg+QNlL79I46wvWZTcf21+0DhMMQTOGipMek8zBNwIJVlzctUMBlpFuhN5NGtlJsjeZ9KqykpOlzqb0bwt+TmEJ4b3WAixtThaf6he9KatAYKPyIHt5vsX3CBk4APIUp1rPzyoxesecHRfdKsjKeHGNOAPKLL6iDMS2YRjqru3wTt+GfNx8fcK3vZNCs1p/nTYcVExxkzuACVEuql9BjY9kXruV+mfhm7LcjsztAtSfXYKFuSpBIBEi2iqw=
  file: 
    - builds/MyHome_windows_amd64.exe
    - builds/MyHome_darwin_amd64
    - builds/MyHome_linux_amd64
  on:
    repo: helto4real/MyHome
    branch: dev
    tags: true
    condition: $LATEST = true
